name: testnem a zabalime

on:
  push:
    tags:
      - 'zip-*'

jobs:
  testik_a_zip:               
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - run: echo "Testujeme"
              
      - name: Zapnem test
        run: python -m unittest test_soucet.py

      - run: echo "Test super jdeme balit" 

      - name: zipujeme
        run: zip balicek.zip soucet.py
